# These are supported funding model platforms
Website: https://wowhellgarve.com/legion/en/donate
ko_fi: https://ko-fi.com/wowhellgarve_kyriancore
Patreon: https://www.patreon.com/bePatron?u=2880461
Paypal: https://www.paypal.com/paypalme/HellgarveLagos
